//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("karyasampannaModel", "FK__Cart__plid__1ED998B2", "PaymentList", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(karyasampannaModel.PaymentList), "Cart", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(karyasampannaModel.Cart))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("karyasampannaModel", "FK__Carts__uid__31EC6D26", "Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(karyasampannaModel.Users), "Carts", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(karyasampannaModel.Carts))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("karyasampannaModel", "FK__PaymentLi__pluid__1A14E395", "Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(karyasampannaModel.Users), "PaymentList", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(karyasampannaModel.PaymentList))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("karyasampannaModel", "fk_rid", "roles", global::System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(karyasampannaModel.roles), "Users", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(karyasampannaModel.Users))]

// Original file name:
// Generation date: 11-May-13 4:02:42 PM
namespace karyasampannaModel
{
    
    /// <summary>
    /// There are no comments for karyasampannaEntities in the schema.
    /// </summary>
    public partial class karyasampannaEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new karyasampannaEntities object using the connection string found in the 'karyasampannaEntities' section of the application configuration file.
        /// </summary>
        public karyasampannaEntities() : 
                base("name=karyasampannaEntities", "karyasampannaEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new karyasampannaEntities object.
        /// </summary>
        public karyasampannaEntities(string connectionString) : 
                base(connectionString, "karyasampannaEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new karyasampannaEntities object.
        /// </summary>
        public karyasampannaEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "karyasampannaEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Cart in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Cart> Cart
        {
            get
            {
                if ((this._Cart == null))
                {
                    this._Cart = base.CreateQuery<Cart>("[Cart]");
                }
                return this._Cart;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Cart> _Cart;
        /// <summary>
        /// There are no comments for Carts in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Carts> Carts
        {
            get
            {
                if ((this._Carts == null))
                {
                    this._Carts = base.CreateQuery<Carts>("[Carts]");
                }
                return this._Carts;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Carts> _Carts;
        /// <summary>
        /// There are no comments for foodpackage in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<foodpackage> foodpackage
        {
            get
            {
                if ((this._foodpackage == null))
                {
                    this._foodpackage = base.CreateQuery<foodpackage>("[foodpackage]");
                }
                return this._foodpackage;
            }
        }
        private global::System.Data.Objects.ObjectQuery<foodpackage> _foodpackage;
        /// <summary>
        /// There are no comments for pandit in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<pandit> pandit
        {
            get
            {
                if ((this._pandit == null))
                {
                    this._pandit = base.CreateQuery<pandit>("[pandit]");
                }
                return this._pandit;
            }
        }
        private global::System.Data.Objects.ObjectQuery<pandit> _pandit;
        /// <summary>
        /// There are no comments for PaymentList in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<PaymentList> PaymentList
        {
            get
            {
                if ((this._PaymentList == null))
                {
                    this._PaymentList = base.CreateQuery<PaymentList>("[PaymentList]");
                }
                return this._PaymentList;
            }
        }
        private global::System.Data.Objects.ObjectQuery<PaymentList> _PaymentList;
        /// <summary>
        /// There are no comments for poojasamagri in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<poojasamagri> poojasamagri
        {
            get
            {
                if ((this._poojasamagri == null))
                {
                    this._poojasamagri = base.CreateQuery<poojasamagri>("[poojasamagri]");
                }
                return this._poojasamagri;
            }
        }
        private global::System.Data.Objects.ObjectQuery<poojasamagri> _poojasamagri;
        /// <summary>
        /// There are no comments for roles in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<roles> roles
        {
            get
            {
                if ((this._roles == null))
                {
                    this._roles = base.CreateQuery<roles>("[roles]");
                }
                return this._roles;
            }
        }
        private global::System.Data.Objects.ObjectQuery<roles> _roles;
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Users> Users
        {
            get
            {
                if ((this._Users == null))
                {
                    this._Users = base.CreateQuery<Users>("[Users]");
                }
                return this._Users;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Users> _Users;
        /// <summary>
        /// There are no comments for creditcard in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<creditcard> creditcard
        {
            get
            {
                if ((this._creditcard == null))
                {
                    this._creditcard = base.CreateQuery<creditcard>("[creditcard]");
                }
                return this._creditcard;
            }
        }
        private global::System.Data.Objects.ObjectQuery<creditcard> _creditcard;
        /// <summary>
        /// There are no comments for Cart in the schema.
        /// </summary>
        public void AddToCart(Cart cart)
        {
            base.AddObject("Cart", cart);
        }
        /// <summary>
        /// There are no comments for Carts in the schema.
        /// </summary>
        public void AddToCarts(Carts carts)
        {
            base.AddObject("Carts", carts);
        }
        /// <summary>
        /// There are no comments for foodpackage in the schema.
        /// </summary>
        public void AddTofoodpackage(foodpackage foodpackage)
        {
            base.AddObject("foodpackage", foodpackage);
        }
        /// <summary>
        /// There are no comments for pandit in the schema.
        /// </summary>
        public void AddTopandit(pandit pandit)
        {
            base.AddObject("pandit", pandit);
        }
        /// <summary>
        /// There are no comments for PaymentList in the schema.
        /// </summary>
        public void AddToPaymentList(PaymentList paymentList)
        {
            base.AddObject("PaymentList", paymentList);
        }
        /// <summary>
        /// There are no comments for poojasamagri in the schema.
        /// </summary>
        public void AddTopoojasamagri(poojasamagri poojasamagri)
        {
            base.AddObject("poojasamagri", poojasamagri);
        }
        /// <summary>
        /// There are no comments for roles in the schema.
        /// </summary>
        public void AddToroles(roles roles)
        {
            base.AddObject("roles", roles);
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }
        /// <summary>
        /// There are no comments for creditcard in the schema.
        /// </summary>
        public void AddTocreditcard(creditcard creditcard)
        {
            base.AddObject("creditcard", creditcard);
        }
    }
    /// <summary>
    /// There are no comments for karyasampannaModel.Cart in the schema.
    /// </summary>
    /// <KeyProperties>
    /// cid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="karyasampannaModel", Name="Cart")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Cart : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Cart object.
        /// </summary>
        /// <param name="cid">Initial value of cid.</param>
        public static Cart CreateCart(int cid)
        {
            Cart cart = new Cart();
            cart.cid = cid;
            return cart;
        }
        /// <summary>
        /// There are no comments for Property cid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int cid
        {
            get
            {
                return this._cid;
            }
            set
            {
                this.OncidChanging(value);
                this.ReportPropertyChanging("cid");
                this._cid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cid");
                this.OncidChanged();
            }
        }
        private int _cid;
        partial void OncidChanging(int value);
        partial void OncidChanged();
        /// <summary>
        /// There are no comments for Property package in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> package
        {
            get
            {
                return this._package;
            }
            set
            {
                this.OnpackageChanging(value);
                this.ReportPropertyChanging("package");
                this._package = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("package");
                this.OnpackageChanged();
            }
        }
        private global::System.Nullable<int> _package;
        partial void OnpackageChanging(global::System.Nullable<int> value);
        partial void OnpackageChanged();
        /// <summary>
        /// There are no comments for Property price in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> price
        {
            get
            {
                return this._price;
            }
            set
            {
                this.OnpriceChanging(value);
                this.ReportPropertyChanging("price");
                this._price = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("price");
                this.OnpriceChanged();
            }
        }
        private global::System.Nullable<int> _price;
        partial void OnpriceChanging(global::System.Nullable<int> value);
        partial void OnpriceChanged();
        /// <summary>
        /// There are no comments for Property noofpeople in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> noofpeople
        {
            get
            {
                return this._noofpeople;
            }
            set
            {
                this.OnnoofpeopleChanging(value);
                this.ReportPropertyChanging("noofpeople");
                this._noofpeople = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("noofpeople");
                this.OnnoofpeopleChanged();
            }
        }
        private global::System.Nullable<int> _noofpeople;
        partial void OnnoofpeopleChanging(global::System.Nullable<int> value);
        partial void OnnoofpeopleChanged();
        /// <summary>
        /// There are no comments for Property totalprice in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> totalprice
        {
            get
            {
                return this._totalprice;
            }
            set
            {
                this.OntotalpriceChanging(value);
                this.ReportPropertyChanging("totalprice");
                this._totalprice = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("totalprice");
                this.OntotalpriceChanged();
            }
        }
        private global::System.Nullable<long> _totalprice;
        partial void OntotalpriceChanging(global::System.Nullable<long> value);
        partial void OntotalpriceChanged();
        /// <summary>
        /// There are no comments for PaymentList in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("karyasampannaModel", "FK__Cart__plid__1ED998B2", "PaymentList")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public PaymentList PaymentList
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PaymentList>("karyasampannaModel.FK__Cart__plid__1ED998B2", "PaymentList").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PaymentList>("karyasampannaModel.FK__Cart__plid__1ED998B2", "PaymentList").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for PaymentList in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<PaymentList> PaymentListReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<PaymentList>("karyasampannaModel.FK__Cart__plid__1ED998B2", "PaymentList");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<PaymentList>("karyasampannaModel.FK__Cart__plid__1ED998B2", "PaymentList", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for karyasampannaModel.Carts in the schema.
    /// </summary>
    /// <KeyProperties>
    /// cid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="karyasampannaModel", Name="Carts")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Carts : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Carts object.
        /// </summary>
        /// <param name="cid">Initial value of cid.</param>
        public static Carts CreateCarts(int cid)
        {
            Carts carts = new Carts();
            carts.cid = cid;
            return carts;
        }
        /// <summary>
        /// There are no comments for Property cid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int cid
        {
            get
            {
                return this._cid;
            }
            set
            {
                this.OncidChanging(value);
                this.ReportPropertyChanging("cid");
                this._cid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cid");
                this.OncidChanged();
            }
        }
        private int _cid;
        partial void OncidChanging(int value);
        partial void OncidChanged();
        /// <summary>
        /// There are no comments for Property pack1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> pack1
        {
            get
            {
                return this._pack1;
            }
            set
            {
                this.Onpack1Changing(value);
                this.ReportPropertyChanging("pack1");
                this._pack1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pack1");
                this.Onpack1Changed();
            }
        }
        private global::System.Nullable<bool> _pack1;
        partial void Onpack1Changing(global::System.Nullable<bool> value);
        partial void Onpack1Changed();
        /// <summary>
        /// There are no comments for Property pack2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> pack2
        {
            get
            {
                return this._pack2;
            }
            set
            {
                this.Onpack2Changing(value);
                this.ReportPropertyChanging("pack2");
                this._pack2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pack2");
                this.Onpack2Changed();
            }
        }
        private global::System.Nullable<bool> _pack2;
        partial void Onpack2Changing(global::System.Nullable<bool> value);
        partial void Onpack2Changed();
        /// <summary>
        /// There are no comments for Property pack3 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> pack3
        {
            get
            {
                return this._pack3;
            }
            set
            {
                this.Onpack3Changing(value);
                this.ReportPropertyChanging("pack3");
                this._pack3 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pack3");
                this.Onpack3Changed();
            }
        }
        private global::System.Nullable<bool> _pack3;
        partial void Onpack3Changing(global::System.Nullable<bool> value);
        partial void Onpack3Changed();
        /// <summary>
        /// There are no comments for Property pack4 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> pack4
        {
            get
            {
                return this._pack4;
            }
            set
            {
                this.Onpack4Changing(value);
                this.ReportPropertyChanging("pack4");
                this._pack4 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pack4");
                this.Onpack4Changed();
            }
        }
        private global::System.Nullable<bool> _pack4;
        partial void Onpack4Changing(global::System.Nullable<bool> value);
        partial void Onpack4Changed();
        /// <summary>
        /// There are no comments for Property pack5 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> pack5
        {
            get
            {
                return this._pack5;
            }
            set
            {
                this.Onpack5Changing(value);
                this.ReportPropertyChanging("pack5");
                this._pack5 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pack5");
                this.Onpack5Changed();
            }
        }
        private global::System.Nullable<bool> _pack5;
        partial void Onpack5Changing(global::System.Nullable<bool> value);
        partial void Onpack5Changed();
        /// <summary>
        /// There are no comments for Property pack6 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> pack6
        {
            get
            {
                return this._pack6;
            }
            set
            {
                this.Onpack6Changing(value);
                this.ReportPropertyChanging("pack6");
                this._pack6 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pack6");
                this.Onpack6Changed();
            }
        }
        private global::System.Nullable<bool> _pack6;
        partial void Onpack6Changing(global::System.Nullable<bool> value);
        partial void Onpack6Changed();
        /// <summary>
        /// There are no comments for Property pack7 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> pack7
        {
            get
            {
                return this._pack7;
            }
            set
            {
                this.Onpack7Changing(value);
                this.ReportPropertyChanging("pack7");
                this._pack7 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pack7");
                this.Onpack7Changed();
            }
        }
        private global::System.Nullable<bool> _pack7;
        partial void Onpack7Changing(global::System.Nullable<bool> value);
        partial void Onpack7Changed();
        /// <summary>
        /// There are no comments for Property pack8 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> pack8
        {
            get
            {
                return this._pack8;
            }
            set
            {
                this.Onpack8Changing(value);
                this.ReportPropertyChanging("pack8");
                this._pack8 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pack8");
                this.Onpack8Changed();
            }
        }
        private global::System.Nullable<bool> _pack8;
        partial void Onpack8Changing(global::System.Nullable<bool> value);
        partial void Onpack8Changed();
        /// <summary>
        /// There are no comments for Property pack9 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> pack9
        {
            get
            {
                return this._pack9;
            }
            set
            {
                this.Onpack9Changing(value);
                this.ReportPropertyChanging("pack9");
                this._pack9 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pack9");
                this.Onpack9Changed();
            }
        }
        private global::System.Nullable<bool> _pack9;
        partial void Onpack9Changing(global::System.Nullable<bool> value);
        partial void Onpack9Changed();
        /// <summary>
        /// There are no comments for Property pack10 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> pack10
        {
            get
            {
                return this._pack10;
            }
            set
            {
                this.Onpack10Changing(value);
                this.ReportPropertyChanging("pack10");
                this._pack10 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pack10");
                this.Onpack10Changed();
            }
        }
        private global::System.Nullable<bool> _pack10;
        partial void Onpack10Changing(global::System.Nullable<bool> value);
        partial void Onpack10Changed();
        /// <summary>
        /// There are no comments for Property pack11 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> pack11
        {
            get
            {
                return this._pack11;
            }
            set
            {
                this.Onpack11Changing(value);
                this.ReportPropertyChanging("pack11");
                this._pack11 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pack11");
                this.Onpack11Changed();
            }
        }
        private global::System.Nullable<bool> _pack11;
        partial void Onpack11Changing(global::System.Nullable<bool> value);
        partial void Onpack11Changed();
        /// <summary>
        /// There are no comments for Property pack12 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> pack12
        {
            get
            {
                return this._pack12;
            }
            set
            {
                this.Onpack12Changing(value);
                this.ReportPropertyChanging("pack12");
                this._pack12 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pack12");
                this.Onpack12Changed();
            }
        }
        private global::System.Nullable<bool> _pack12;
        partial void Onpack12Changing(global::System.Nullable<bool> value);
        partial void Onpack12Changed();
        /// <summary>
        /// There are no comments for Property pack13 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> pack13
        {
            get
            {
                return this._pack13;
            }
            set
            {
                this.Onpack13Changing(value);
                this.ReportPropertyChanging("pack13");
                this._pack13 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pack13");
                this.Onpack13Changed();
            }
        }
        private global::System.Nullable<bool> _pack13;
        partial void Onpack13Changing(global::System.Nullable<bool> value);
        partial void Onpack13Changed();
        /// <summary>
        /// There are no comments for Property pack14 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> pack14
        {
            get
            {
                return this._pack14;
            }
            set
            {
                this.Onpack14Changing(value);
                this.ReportPropertyChanging("pack14");
                this._pack14 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pack14");
                this.Onpack14Changed();
            }
        }
        private global::System.Nullable<bool> _pack14;
        partial void Onpack14Changing(global::System.Nullable<bool> value);
        partial void Onpack14Changed();
        /// <summary>
        /// There are no comments for Property pack15 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> pack15
        {
            get
            {
                return this._pack15;
            }
            set
            {
                this.Onpack15Changing(value);
                this.ReportPropertyChanging("pack15");
                this._pack15 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pack15");
                this.Onpack15Changed();
            }
        }
        private global::System.Nullable<bool> _pack15;
        partial void Onpack15Changing(global::System.Nullable<bool> value);
        partial void Onpack15Changed();
        /// <summary>
        /// There are no comments for Property pack16 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> pack16
        {
            get
            {
                return this._pack16;
            }
            set
            {
                this.Onpack16Changing(value);
                this.ReportPropertyChanging("pack16");
                this._pack16 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pack16");
                this.Onpack16Changed();
            }
        }
        private global::System.Nullable<bool> _pack16;
        partial void Onpack16Changing(global::System.Nullable<bool> value);
        partial void Onpack16Changed();
        /// <summary>
        /// There are no comments for Property pack17 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> pack17
        {
            get
            {
                return this._pack17;
            }
            set
            {
                this.Onpack17Changing(value);
                this.ReportPropertyChanging("pack17");
                this._pack17 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pack17");
                this.Onpack17Changed();
            }
        }
        private global::System.Nullable<bool> _pack17;
        partial void Onpack17Changing(global::System.Nullable<bool> value);
        partial void Onpack17Changed();
        /// <summary>
        /// There are no comments for Property pack18 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> pack18
        {
            get
            {
                return this._pack18;
            }
            set
            {
                this.Onpack18Changing(value);
                this.ReportPropertyChanging("pack18");
                this._pack18 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pack18");
                this.Onpack18Changed();
            }
        }
        private global::System.Nullable<bool> _pack18;
        partial void Onpack18Changing(global::System.Nullable<bool> value);
        partial void Onpack18Changed();
        /// <summary>
        /// There are no comments for Property creditcardno in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> creditcardno
        {
            get
            {
                return this._creditcardno;
            }
            set
            {
                this.OncreditcardnoChanging(value);
                this.ReportPropertyChanging("creditcardno");
                this._creditcardno = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("creditcardno");
                this.OncreditcardnoChanged();
            }
        }
        private global::System.Nullable<long> _creditcardno;
        partial void OncreditcardnoChanging(global::System.Nullable<long> value);
        partial void OncreditcardnoChanged();
        /// <summary>
        /// There are no comments for Property cvvcode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> cvvcode
        {
            get
            {
                return this._cvvcode;
            }
            set
            {
                this.OncvvcodeChanging(value);
                this.ReportPropertyChanging("cvvcode");
                this._cvvcode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("cvvcode");
                this.OncvvcodeChanged();
            }
        }
        private global::System.Nullable<int> _cvvcode;
        partial void OncvvcodeChanging(global::System.Nullable<int> value);
        partial void OncvvcodeChanged();
        /// <summary>
        /// There are no comments for Property amount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> amount
        {
            get
            {
                return this._amount;
            }
            set
            {
                this.OnamountChanging(value);
                this.ReportPropertyChanging("amount");
                this._amount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("amount");
                this.OnamountChanged();
            }
        }
        private global::System.Nullable<int> _amount;
        partial void OnamountChanging(global::System.Nullable<int> value);
        partial void OnamountChanged();
        /// <summary>
        /// There are no comments for Property pdate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> pdate
        {
            get
            {
                return this._pdate;
            }
            set
            {
                this.OnpdateChanging(value);
                this.ReportPropertyChanging("pdate");
                this._pdate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pdate");
                this.OnpdateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _pdate;
        partial void OnpdateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnpdateChanged();
        /// <summary>
        /// There are no comments for Property paid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<bool> paid
        {
            get
            {
                return this._paid;
            }
            set
            {
                this.OnpaidChanging(value);
                this.ReportPropertyChanging("paid");
                this._paid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("paid");
                this.OnpaidChanged();
            }
        }
        private global::System.Nullable<bool> _paid;
        partial void OnpaidChanging(global::System.Nullable<bool> value);
        partial void OnpaidChanged();
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("karyasampannaModel", "FK__Carts__uid__31EC6D26", "Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Users Users
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("karyasampannaModel.FK__Carts__uid__31EC6D26", "Users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("karyasampannaModel.FK__Carts__uid__31EC6D26", "Users").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Users> UsersReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("karyasampannaModel.FK__Carts__uid__31EC6D26", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Users>("karyasampannaModel.FK__Carts__uid__31EC6D26", "Users", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for karyasampannaModel.foodpackage in the schema.
    /// </summary>
    /// <KeyProperties>
    /// fid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="karyasampannaModel", Name="foodpackage")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class foodpackage : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new foodpackage object.
        /// </summary>
        /// <param name="fid">Initial value of fid.</param>
        public static foodpackage Createfoodpackage(int fid)
        {
            foodpackage foodpackage = new foodpackage();
            foodpackage.fid = fid;
            return foodpackage;
        }
        /// <summary>
        /// There are no comments for Property fid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int fid
        {
            get
            {
                return this._fid;
            }
            set
            {
                this.OnfidChanging(value);
                this.ReportPropertyChanging("fid");
                this._fid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fid");
                this.OnfidChanged();
            }
        }
        private int _fid;
        partial void OnfidChanging(int value);
        partial void OnfidChanged();
        /// <summary>
        /// There are no comments for Property fname in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string fname
        {
            get
            {
                return this._fname;
            }
            set
            {
                this.OnfnameChanging(value);
                this.ReportPropertyChanging("fname");
                this._fname = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("fname");
                this.OnfnameChanged();
            }
        }
        private string _fname;
        partial void OnfnameChanging(string value);
        partial void OnfnameChanged();
        /// <summary>
        /// There are no comments for Property fprice in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> fprice
        {
            get
            {
                return this._fprice;
            }
            set
            {
                this.OnfpriceChanging(value);
                this.ReportPropertyChanging("fprice");
                this._fprice = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("fprice");
                this.OnfpriceChanged();
            }
        }
        private global::System.Nullable<int> _fprice;
        partial void OnfpriceChanging(global::System.Nullable<int> value);
        partial void OnfpriceChanged();
        /// <summary>
        /// There are no comments for Property fdescription in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string fdescription
        {
            get
            {
                return this._fdescription;
            }
            set
            {
                this.OnfdescriptionChanging(value);
                this.ReportPropertyChanging("fdescription");
                this._fdescription = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("fdescription");
                this.OnfdescriptionChanged();
            }
        }
        private string _fdescription;
        partial void OnfdescriptionChanging(string value);
        partial void OnfdescriptionChanged();
    }
    /// <summary>
    /// There are no comments for karyasampannaModel.pandit in the schema.
    /// </summary>
    /// <KeyProperties>
    /// paid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="karyasampannaModel", Name="pandit")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class pandit : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new pandit object.
        /// </summary>
        /// <param name="paid">Initial value of paid.</param>
        public static pandit Createpandit(int paid)
        {
            pandit pandit = new pandit();
            pandit.paid = paid;
            return pandit;
        }
        /// <summary>
        /// There are no comments for Property paid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int paid
        {
            get
            {
                return this._paid;
            }
            set
            {
                this.OnpaidChanging(value);
                this.ReportPropertyChanging("paid");
                this._paid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("paid");
                this.OnpaidChanged();
            }
        }
        private int _paid;
        partial void OnpaidChanging(int value);
        partial void OnpaidChanged();
        /// <summary>
        /// There are no comments for Property paname in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string paname
        {
            get
            {
                return this._paname;
            }
            set
            {
                this.OnpanameChanging(value);
                this.ReportPropertyChanging("paname");
                this._paname = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("paname");
                this.OnpanameChanged();
            }
        }
        private string _paname;
        partial void OnpanameChanging(string value);
        partial void OnpanameChanged();
        /// <summary>
        /// There are no comments for Property paprice in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> paprice
        {
            get
            {
                return this._paprice;
            }
            set
            {
                this.OnpapriceChanging(value);
                this.ReportPropertyChanging("paprice");
                this._paprice = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("paprice");
                this.OnpapriceChanged();
            }
        }
        private global::System.Nullable<int> _paprice;
        partial void OnpapriceChanging(global::System.Nullable<int> value);
        partial void OnpapriceChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this.ReportPropertyChanging("description");
                this._description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("description");
                this.OndescriptionChanged();
            }
        }
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
    }
    /// <summary>
    /// There are no comments for karyasampannaModel.PaymentList in the schema.
    /// </summary>
    /// <KeyProperties>
    /// plid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="karyasampannaModel", Name="PaymentList")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PaymentList : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PaymentList object.
        /// </summary>
        /// <param name="plid">Initial value of plid.</param>
        public static PaymentList CreatePaymentList(int plid)
        {
            PaymentList paymentList = new PaymentList();
            paymentList.plid = plid;
            return paymentList;
        }
        /// <summary>
        /// There are no comments for Property plid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int plid
        {
            get
            {
                return this._plid;
            }
            set
            {
                this.OnplidChanging(value);
                this.ReportPropertyChanging("plid");
                this._plid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("plid");
                this.OnplidChanged();
            }
        }
        private int _plid;
        partial void OnplidChanging(int value);
        partial void OnplidChanged();
        /// <summary>
        /// There are no comments for Property plcreditcardno in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string plcreditcardno
        {
            get
            {
                return this._plcreditcardno;
            }
            set
            {
                this.OnplcreditcardnoChanging(value);
                this.ReportPropertyChanging("plcreditcardno");
                this._plcreditcardno = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("plcreditcardno");
                this.OnplcreditcardnoChanged();
            }
        }
        private string _plcreditcardno;
        partial void OnplcreditcardnoChanging(string value);
        partial void OnplcreditcardnoChanged();
        /// <summary>
        /// There are no comments for Property pldate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> pldate
        {
            get
            {
                return this._pldate;
            }
            set
            {
                this.OnpldateChanging(value);
                this.ReportPropertyChanging("pldate");
                this._pldate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pldate");
                this.OnpldateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _pldate;
        partial void OnpldateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnpldateChanged();
        /// <summary>
        /// There are no comments for Property amount in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<long> amount
        {
            get
            {
                return this._amount;
            }
            set
            {
                this.OnamountChanging(value);
                this.ReportPropertyChanging("amount");
                this._amount = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("amount");
                this.OnamountChanged();
            }
        }
        private global::System.Nullable<long> _amount;
        partial void OnamountChanging(global::System.Nullable<long> value);
        partial void OnamountChanged();
        /// <summary>
        /// There are no comments for Cart in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("karyasampannaModel", "FK__Cart__plid__1ED998B2", "Cart")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Cart> Cart
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Cart>("karyasampannaModel.FK__Cart__plid__1ED998B2", "Cart");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Cart>("karyasampannaModel.FK__Cart__plid__1ED998B2", "Cart", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("karyasampannaModel", "FK__PaymentLi__pluid__1A14E395", "Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Users Users
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("karyasampannaModel.FK__PaymentLi__pluid__1A14E395", "Users").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("karyasampannaModel.FK__PaymentLi__pluid__1A14E395", "Users").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Users> UsersReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Users>("karyasampannaModel.FK__PaymentLi__pluid__1A14E395", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Users>("karyasampannaModel.FK__PaymentLi__pluid__1A14E395", "Users", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for karyasampannaModel.poojasamagri in the schema.
    /// </summary>
    /// <KeyProperties>
    /// pid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="karyasampannaModel", Name="poojasamagri")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class poojasamagri : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new poojasamagri object.
        /// </summary>
        /// <param name="pid">Initial value of pid.</param>
        public static poojasamagri Createpoojasamagri(int pid)
        {
            poojasamagri poojasamagri = new poojasamagri();
            poojasamagri.pid = pid;
            return poojasamagri;
        }
        /// <summary>
        /// There are no comments for Property pid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int pid
        {
            get
            {
                return this._pid;
            }
            set
            {
                this.OnpidChanging(value);
                this.ReportPropertyChanging("pid");
                this._pid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("pid");
                this.OnpidChanged();
            }
        }
        private int _pid;
        partial void OnpidChanging(int value);
        partial void OnpidChanged();
        /// <summary>
        /// There are no comments for Property pname in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string pname
        {
            get
            {
                return this._pname;
            }
            set
            {
                this.OnpnameChanging(value);
                this.ReportPropertyChanging("pname");
                this._pname = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("pname");
                this.OnpnameChanged();
            }
        }
        private string _pname;
        partial void OnpnameChanging(string value);
        partial void OnpnameChanged();
        /// <summary>
        /// There are no comments for Property price in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<int> price
        {
            get
            {
                return this._price;
            }
            set
            {
                this.OnpriceChanging(value);
                this.ReportPropertyChanging("price");
                this._price = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("price");
                this.OnpriceChanged();
            }
        }
        private global::System.Nullable<int> _price;
        partial void OnpriceChanging(global::System.Nullable<int> value);
        partial void OnpriceChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this.ReportPropertyChanging("description");
                this._description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("description");
                this.OndescriptionChanged();
            }
        }
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
    }
    /// <summary>
    /// There are no comments for karyasampannaModel.roles in the schema.
    /// </summary>
    /// <KeyProperties>
    /// rid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="karyasampannaModel", Name="roles")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class roles : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new roles object.
        /// </summary>
        /// <param name="rid">Initial value of rid.</param>
        public static roles Createroles(int rid)
        {
            roles roles = new roles();
            roles.rid = rid;
            return roles;
        }
        /// <summary>
        /// There are no comments for Property rid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int rid
        {
            get
            {
                return this._rid;
            }
            set
            {
                this.OnridChanging(value);
                this.ReportPropertyChanging("rid");
                this._rid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("rid");
                this.OnridChanged();
            }
        }
        private int _rid;
        partial void OnridChanging(int value);
        partial void OnridChanged();
        /// <summary>
        /// There are no comments for Property rname in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string rname
        {
            get
            {
                return this._rname;
            }
            set
            {
                this.OnrnameChanging(value);
                this.ReportPropertyChanging("rname");
                this._rname = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("rname");
                this.OnrnameChanged();
            }
        }
        private string _rname;
        partial void OnrnameChanging(string value);
        partial void OnrnameChanged();
        /// <summary>
        /// There are no comments for Users in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("karyasampannaModel", "fk_rid", "Users")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Users> Users
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Users>("karyasampannaModel.fk_rid", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Users>("karyasampannaModel.fk_rid", "Users", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for karyasampannaModel.Users in the schema.
    /// </summary>
    /// <KeyProperties>
    /// uid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="karyasampannaModel", Name="Users")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Users : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="uid">Initial value of uid.</param>
        public static Users CreateUsers(int uid)
        {
            Users users = new Users();
            users.uid = uid;
            return users;
        }
        /// <summary>
        /// There are no comments for Property uid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int uid
        {
            get
            {
                return this._uid;
            }
            set
            {
                this.OnuidChanging(value);
                this.ReportPropertyChanging("uid");
                this._uid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("uid");
                this.OnuidChanged();
            }
        }
        private int _uid;
        partial void OnuidChanging(int value);
        partial void OnuidChanged();
        /// <summary>
        /// There are no comments for Property username in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this._username;
            }
            set
            {
                this.OnusernameChanging(value);
                this.ReportPropertyChanging("username");
                this._username = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("username");
                this.OnusernameChanged();
            }
        }
        private string _username;
        partial void OnusernameChanging(string value);
        partial void OnusernameChanged();
        /// <summary>
        /// There are no comments for Property upassword in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string upassword
        {
            get
            {
                return this._upassword;
            }
            set
            {
                this.OnupasswordChanging(value);
                this.ReportPropertyChanging("upassword");
                this._upassword = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("upassword");
                this.OnupasswordChanged();
            }
        }
        private string _upassword;
        partial void OnupasswordChanging(string value);
        partial void OnupasswordChanged();
        /// <summary>
        /// There are no comments for Property uName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string uName
        {
            get
            {
                return this._uName;
            }
            set
            {
                this.OnuNameChanging(value);
                this.ReportPropertyChanging("uName");
                this._uName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("uName");
                this.OnuNameChanged();
            }
        }
        private string _uName;
        partial void OnuNameChanging(string value);
        partial void OnuNameChanged();
        /// <summary>
        /// There are no comments for Property uAddress in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string uAddress
        {
            get
            {
                return this._uAddress;
            }
            set
            {
                this.OnuAddressChanging(value);
                this.ReportPropertyChanging("uAddress");
                this._uAddress = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("uAddress");
                this.OnuAddressChanged();
            }
        }
        private string _uAddress;
        partial void OnuAddressChanging(string value);
        partial void OnuAddressChanged();
        /// <summary>
        /// There are no comments for Property uCountry in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string uCountry
        {
            get
            {
                return this._uCountry;
            }
            set
            {
                this.OnuCountryChanging(value);
                this.ReportPropertyChanging("uCountry");
                this._uCountry = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("uCountry");
                this.OnuCountryChanged();
            }
        }
        private string _uCountry;
        partial void OnuCountryChanging(string value);
        partial void OnuCountryChanged();
        /// <summary>
        /// There are no comments for Property uState in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string uState
        {
            get
            {
                return this._uState;
            }
            set
            {
                this.OnuStateChanging(value);
                this.ReportPropertyChanging("uState");
                this._uState = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("uState");
                this.OnuStateChanged();
            }
        }
        private string _uState;
        partial void OnuStateChanging(string value);
        partial void OnuStateChanged();
        /// <summary>
        /// There are no comments for Property uCity in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string uCity
        {
            get
            {
                return this._uCity;
            }
            set
            {
                this.OnuCityChanging(value);
                this.ReportPropertyChanging("uCity");
                this._uCity = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("uCity");
                this.OnuCityChanged();
            }
        }
        private string _uCity;
        partial void OnuCityChanging(string value);
        partial void OnuCityChanged();
        /// <summary>
        /// There are no comments for Property uContact in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string uContact
        {
            get
            {
                return this._uContact;
            }
            set
            {
                this.OnuContactChanging(value);
                this.ReportPropertyChanging("uContact");
                this._uContact = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("uContact");
                this.OnuContactChanged();
            }
        }
        private string _uContact;
        partial void OnuContactChanging(string value);
        partial void OnuContactChanged();
        /// <summary>
        /// There are no comments for Carts in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("karyasampannaModel", "FK__Carts__uid__31EC6D26", "Carts")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Carts> Carts
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Carts>("karyasampannaModel.FK__Carts__uid__31EC6D26", "Carts");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Carts>("karyasampannaModel.FK__Carts__uid__31EC6D26", "Carts", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for PaymentList in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("karyasampannaModel", "FK__PaymentLi__pluid__1A14E395", "PaymentList")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PaymentList> PaymentList
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PaymentList>("karyasampannaModel.FK__PaymentLi__pluid__1A14E395", "PaymentList");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PaymentList>("karyasampannaModel.FK__PaymentLi__pluid__1A14E395", "PaymentList", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for roles in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("karyasampannaModel", "fk_rid", "roles")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public roles roles
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<roles>("karyasampannaModel.fk_rid", "roles").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<roles>("karyasampannaModel.fk_rid", "roles").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for roles in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<roles> rolesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<roles>("karyasampannaModel.fk_rid", "roles");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<roles>("karyasampannaModel.fk_rid", "roles", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for karyasampannaModel.creditcard in the schema.
    /// </summary>
    /// <KeyProperties>
    /// crid
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="karyasampannaModel", Name="creditcard")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class creditcard : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new creditcard object.
        /// </summary>
        /// <param name="crid">Initial value of crid.</param>
        public static creditcard Createcreditcard(int crid)
        {
            creditcard creditcard = new creditcard();
            creditcard.crid = crid;
            return creditcard;
        }
        /// <summary>
        /// There are no comments for Property crid in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int crid
        {
            get
            {
                return this._crid;
            }
            set
            {
                this.OncridChanging(value);
                this.ReportPropertyChanging("crid");
                this._crid = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("crid");
                this.OncridChanged();
            }
        }
        private int _crid;
        partial void OncridChanging(int value);
        partial void OncridChanged();
        /// <summary>
        /// There are no comments for Property cardnumber in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string cardnumber
        {
            get
            {
                return this._cardnumber;
            }
            set
            {
                this.OncardnumberChanging(value);
                this.ReportPropertyChanging("cardnumber");
                this._cardnumber = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("cardnumber");
                this.OncardnumberChanged();
            }
        }
        private string _cardnumber;
        partial void OncardnumberChanging(string value);
        partial void OncardnumberChanged();
        /// <summary>
        /// There are no comments for Property cvvcode in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string cvvcode
        {
            get
            {
                return this._cvvcode;
            }
            set
            {
                this.OncvvcodeChanging(value);
                this.ReportPropertyChanging("cvvcode");
                this._cvvcode = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("cvvcode");
                this.OncvvcodeChanged();
            }
        }
        private string _cvvcode;
        partial void OncvvcodeChanging(string value);
        partial void OncvvcodeChanged();
    }
}
